### ISSUE TITLE
[US-01] list popular movie and series

### ISSUE THREAD

**Issue by Sven-Lyco** [Sven-Lyco/capstone-project#1]
## Value Proposition

**As a** User
**I need** a list of popular movies and series
**to be able to** get an overview and discover interesting movies or series

## Description

<img src="https://user-images.githubusercontent.com/98020906/159681201-91d543f9-250c-4540-a1da-dcc3202e8d78.png" alt="Picture of User Story 1" width="300">

## Acceptance Criteria
- [x] [TMDB-API](https://www.themoviedb.org/documentation/api) connection should be included to get access to each list
- [x] Each list and poster should display the correct image from the API
- [x] Each List should be displayed in one row
- [x] Each List contains 20 Elements
- [x] Each Poster should contain an alt-attribute `alt="picture of <moviename>/<seriesname>"`

## Tasks

- [x] Create feature branch `list-movies-series`
- [x] Connect to [TMDB-API](https://www.themoviedb.org/documentation/api) and fetch data for movies and series
- [x] Build `Poster` Component with Storybook
- [x] Build `PosterList` with Storybook
- [x] Test `Poster` Component
- [x] Test `PosterList`
- [x] Add `PosterList` to `App`
- [x] Update Styles
- [x] Test on mobile device / different Browser
