### ISSUE TITLE
[US-10] check watched movie

### ISSUE THREAD

**Issue by Sven-Lyco** [Sven-Lyco/capstone-project#10]
## Value Proposition

**As a** User
**I need** a button
**to be able to** set a movie as watched, to remember which movies I have already watched

## Description
<img src="https://user-images.githubusercontent.com/98020906/160187741-83e5c049-7b7a-463b-9096-f502d7ef8113.png" alt="Picture of User Story 10" width="450">

## Acceptance Criteria

- [x] The Watched-Button is displayed, when the movie is on watchlist
- [x] By clicking the Watched-Button it switches the color
- [x] The status of the button persist after reload or closing the app 
- [x] the button should be accessible 

## Tasks

- [x] create feature branch `check-watched-movie`
- [x] build `ButtonCheckMovie` with storybook
- [x] test `ButtonCheckMovie`
- [x] Add Button to Movie-Details-Page
- [x] create function to save the state of the button for each movie with `localStorage()`
- [x] Test on Browser: Safari, Chrome and Firefox with Desktop PC, iPhone 11, iPad Air 2
