### ISSUE TITLE
[US-11] check watched episode

### ISSUE THREAD

**Issue by Sven-Lyco** [Sven-Lyco/capstone-project#11]
## Value Proposition

**As a** User
**I need** an extra button
**to be able to** set an episode as watched, to remember that i watched the episode of a season

## Description
<img src="https://user-images.githubusercontent.com/98020906/160190508-f12b1cad-8c59-4755-a77c-1014c8c414b7.png" alt="Picture of User Story 11" width="450">

## Acceptance Criteria

- [x] The Watched-Button is displayed, when the series is on watchlist
- [x] By clicking the Watched-Button it switches the color
- [x] The status of the button persist after reload or closing the app
- [x] The button should be accessible 

## Tasks

- [x] create feature branch `check-watched-episode`
- [x] build `ButtonCheckEpisode` with storybook
- [x] test `ButtonCheckEpisode`
- [x] Add Button to `EpisodeCard`
- [x] create function to save the state of the button for each movie with `localStorage()`
- [x] Test on Browser: Safari, Chrome and Firefox with Desktop PC, iPhone 11, iPad Air 2
