### ISSUE TITLE
[US-12] add search

### ISSUE THREAD

**Issue by Sven-Lyco** [Sven-Lyco/capstone-project#12]
## Value Proposition

**As a** User
**I need** a searchpage
**to be able to** search for movies and series, i want to watch

## Description
<img src="https://user-images.githubusercontent.com/98020906/160286874-6b972fcf-5999-47cc-a9cf-6f31fa08cb7e.png" alt="Picture of User Story 12" width="500">

## Acceptance Criteria

- [x] an inputfield for search is on top of the page
- [x] the navigation is updated with a Search-Icon
- [x] the search, searches for series and movies
- [x] search results are displayed as a list
- [x] If the search doesn't find entries or search is empty, an information should be displayed

## Tasks

- [x] create feature branch `search-page`
- [x] update `Navigation` with Storybook and Testing
- [x] create a `Search` -Page
- [x] test `Search` -Page
- [x] add `Search` -Page to `App`
- [x] test on Browser: Safari, Chrome and Firefox with Desktop PC, iPhone 11, iPad Air 2
