### ISSUE TITLE
[US-13] code refactoring

### ISSUE THREAD

**Issue by Sven-Lyco** [Sven-Lyco/capstone-project#15]
## Value Proposition

**As a** Developer
**I need** an app with clean code
**to be able to** maintain the app more easily

## Description

Code refactoring

## Acceptance Criteria

- [x] The length of the code is reduced and more efficient

## Tasks

- [x] create feature branch `code-refactoring`
- [x] Update README.md
- [x] look for unnecessary code
- [x] check/update specs
- [x] check/update stories
- [x] check accessibility
- [x] check that code is semantically correct
- [x] create components for styling purposes if necessary
- [x] test on browser: Safari, Chrome and Firefox with Desktop PC, iPhone 11, iPad Air 2
