### ISSUE TITLE
[US-14]404-Page

### ISSUE THREAD

**Issue by Sven-Lyco** [Sven-Lyco/capstone-project#18]
## Value Proposition

**As a** User
**I need** an Error-Page
**to be able to** know that i am on a wrong page and can go back to the main page

## Description

<img src="https://user-images.githubusercontent.com/98020906/161095422-9286308a-fe25-4c6c-ab0f-fab88f5d958c.png" alt="Picture of User Story 14" width="300">

## Acceptance Criteria

- [x] The Error-Page is shown, when the URL is not found
- [x] The User can go back to the Main Page with a Link

## Tasks

- [x] Create feature branch `error-page`
- [x] Create `NotFound` Page
- [x] Test `NotFound` Page
- [x] Add `NotFound` Page to App
- [x] Test on Browser: Safari, Chrome and Firefox with Desktop PC, iPhone 11, iPad Air 2
