### ISSUE TITLE
[US-02] specific lists for movies and series

### ISSUE THREAD

**Issue by Sven-Lyco** [Sven-Lyco/capstone-project#2]
## Value Proposition

**As a** User
**I need** more lists of movies and series
**to be able to** get a wider selection of series and movies

## Description

<img src="https://user-images.githubusercontent.com/98020906/159681293-486ee21c-af12-4a2f-8164-958666f86186.png" alt="Picture of User Story 2" height="400">

## Acceptance Criteria

- [x] A navigation is implemented with React Router
- [x] One page displays either three lists of series or movies

## Tasks

- [x] Create feature branch `specific-lists`
- [x] Create Page `Series`
- [x] Create Page `Movies`
- [x] Build `Navigation` Component with Storybook
- [x] Test `Navigation`
- [x] Add `Navigation` to App
- [x] Add `Series` Page and `Movies` Page to App
- [x] Check each `PosterList`
- [x] Update Styles
- [x] Test on mobile device and different browser
