### ISSUE TITLE
[US-15] show info for failed fetch

### ISSUE THREAD

**Issue by Sven-Lyco** [Sven-Lyco/capstone-project#21]
## Value Proposition

**As a** User
**I need** an information
**to be able to** to know that the data cannot be loaded

## Description

An information text is displayed with a reload button so that the user knows what happened.

## Acceptance Criteria

- [x] An information text is shown, when th fetch doesn't return data
- [x] A reload button refreshes the page

## Tasks

- [x] Create feature branch `error-fetch`
- [x] Create `FetchError` Component with Storybook and a Reload Button
- [x] Write Specs
- [x] Add `FetchError` Component to each Page where fetch is included
- [x] Test on Browser: Safari, Chrome and Firefox with Desktop PC, iPhone 11, iPad Air 2
