### ISSUE TITLE
[US-16] age check

### ISSUE THREAD

**Issue by Sven-Lyco** [Sven-Lyco/capstone-project#23]
## Value Proposition

**As a** developer
**I need** to check the Age of the User
**to be able to** know the User is older than 18

## Description

<img src="https://user-images.githubusercontent.com/98020906/161522871-e55bf620-e864-4f84-89e7-ce05e395e07f.png" alt="Picture of User Story 16" width="500">

## Acceptance Criteria

- [x] An information text is displayed when the app is opened
- [x] if the User is under 18, one more information text will be displayed
- [x] if the User is 18 or older, he can use the App

## Tasks

- [x] create feature branch `age-check`
- [x] create buttons with styled components
- [x] write function for Age Check
- [x] Add Age Check Page to `Home.js`
- [x] Test on Browser: Safari, Chrome and Firefox with Desktop PC, iPhone 11, iPad Air 2
