### ISSUE TITLE
[US-17] backend-fetch

### ISSUE THREAD

**Issue by Sven-Lyco** [Sven-Lyco/capstone-project#25]
## Value Proposition

**As a** Developer
**I need** to fetch data from the backend
**to be able to** have a better perfomance and keep my API-Key as a secret

## Description

implement backend with vercel to fetch data from the API

## Acceptance Criteria

- [x] gets data from back-end
- [x] doesn't send request to the api from the front-end

## Tasks

- [x] create feature branch `backend-fetch`
- [x] install vercel
- [x] create folder `api`
- [x] write functions to fetch data with serverless functions
- [x] update functions to fetch data from backend
- [x] Test on Browser: Safari, Chrome and Firefox with Desktop PC, iPhone 11, iPad Air 2
