### ISSUE TITLE
[US-03] get series details

### ISSUE THREAD

**Issue by Sven-Lyco** [Sven-Lyco/capstone-project#3]
## Value Proposition

**As a** User
**I need** more information about Series
**to be able to** decide which Series I want to watch

## Description

<img src="https://user-images.githubusercontent.com/98020906/159738635-01331362-19ba-4294-a760-e0ca3886a57b.png" alt="Picture of User Story 3" width="600">

## Acceptance Criteria

- [x] The detail page should contain the storyline as shown in the description
- [x] If there is no storyline available, an information text is displayed 
- [x] By clicking on a Poster of a Serie it navigates to a Series details page
- [x] The user should be able to go back to the List
- [x] The Back-Button must be accessible

## Tasks

- [x] Create feature branch `get-series-details`
- [x] Create `SeriesDetails` Page
- [x] Test `SeriesDetails` Page
- [x] Build `ButtonBack` as a component with a Link and an aria-label and storybook
- [x] Test `ButtonBack`
- [x] Add `SeriesDetails` to `App`
- [x] Test on mobile device and different browsers
