### ISSUE TITLE
[US-18] watch providers

### ISSUE THREAD

**Issue by Sven-Lyco** [Sven-Lyco/capstone-project#32]
## Value Proposition

**As a** User
**I need** the watch providers
**to be able to** to know, where i can watch the movie or series

## Description

<img src="https://user-images.githubusercontent.com/98020906/162576115-b868fccf-3ff9-4818-a170-610ea3191782.png" alt="Picture of User Story 18" width="600">

## Acceptance Criteria

- [x] each watch provider is displayed with the logo
- [x] the list of watch providers is scrollable horizontally

## Tasks

- [x] create feature branch `get-watch-providers`
- [x] build two new fetches
   - [x] series watch provider
   - [x] movie watch provider
- [x] update custom Hooks
   - [x] `useSeriesDetails`
   - [x] `useMovieDetails`
- [x] create `WatchProviderList`
   - [x] storybook
   - [x] specs
- [x] Add `watchProviderList` to
   - [x] SeriesDetailsPage
   - [x] MovieDetailsPage
- [x] Test on Browser: Safari, Chrome and Firefox with Desktop PC, iPhone 11, iPad Air 2
