### ISSUE TITLE
[US-20]: Backend Mongo DB

### ISSUE THREAD

**Issue by Sven-Lyco** [Sven-Lyco/capstone-project#35]
## Value Proposition

**As a** User
**I need** a Database
**to be able to** store my Watchlist, watched movies and episodes of series from different devices

## Description

Creation of a back-end to store the watchlist, watched movies and episodes of series permanently

## Acceptance Criteria

- [x] the movies and series on the Watchlist are availlable on different devices
- [x] the user can add and delete movies and series from the watchlist from different devices
- [x] the user can set movies and episodes of series as watched from different devices
- [x] the data will be stored in a database

## Tasks

- [x] create feature branch `database`
- [x] set up mongoDB
- [x] set up Mongoose
- [x] write POST requests in api
- [x] write GET requests in api
- [x] write DELETE request in api
- [x] test MongoDB locally
- [x] set up Cloud-Database with Mongo DB Atlas
- [x] update connection to Database
- [x] test GET, POST and DELETE request
- [x] update custom hooks
- [x] test on Browser: Safari, Chrome and Firefox with Desktop PC, iPhone 11, iPad Air 2
