### ISSUE TITLE
[US-21] similar movies and series

### ISSUE THREAD

**Issue by Sven-Lyco** [Sven-Lyco/capstone-project#39]
## Value Proposition

**As a** User
**I need** more suggestions of movies and series
**to be able to** decide which Series I want to watch

## Description

<img src="https://user-images.githubusercontent.com/98020906/162968176-27706c2d-a141-4814-a91e-c557d03701ee.png" alt="Picture of User Story 21" width="600">

## Acceptance Criteria

- [x] the list of similar series and movies is displayed under the cast
- [x] the lsit of similar series and movies is based on the current movie or series

## Tasks

- [x] create feature branch `get-suggestions`
- [x] create new fetch
- [x] pass the fetched data to the respective detail page
- [x] pass the fetched data to Posterlist
- [x] add Posterlist to detail page of series and movies
- [x] Test on Browser: Safari, Chrome and Firefox with Desktop PC, iPhone 11, iPad Air 2
