### ISSUE TITLE
[US-04] get movie details

### ISSUE THREAD

**Issue by Sven-Lyco** [Sven-Lyco/capstone-project#4]
## Value Proposition

**As a** User
**I need** more information about Movies
**to be able to** decide which Movie I want to watch

## Description

<img src="https://user-images.githubusercontent.com/98020906/159744758-1607718b-f765-43ce-80ed-2d5b9c6ffca0.png" alt="Picture of User Story 3" width="600">

## Acceptance Criteria

- [x] The detail page should contain the storyline as shown in the description
- [x] If there is no storyline available, an information text is displayed
- [x] By clicking on a Poster of a Movie it navigates to a Movie details page
- [x] The user should be able to go back to the List
- [x] The Back-Button must be accessible

## Tasks

- [x] Create feature branch `get-movie-details`
- [x] Create `MovieDetails` Page
- [x] Test `MovieDetails` Page
- [x] Implement and update `ButtonBack`
- [x] Add `MovieDetails` Page to `App`
- [x] Test on mobile device and different browsers
