### ISSUE TITLE
[US-22] trailer videos

### ISSUE THREAD

**Issue by Sven-Lyco** [Sven-Lyco/capstone-project#40]
## Value Proposition

**As a** User
**I need** to see a Trailer of a movie or series
**to be able to** decide which Series I want to watch

## Description

If a video trailer is available, it will be displayed on the detail page of a movie or series instead of the background image.

## Acceptance Criteria

- [x] the videos are only from youtube
- [x] the video has the youtube control panel
- [x] the video starts automatically and muted

## Tasks

- [x] create feature branch `get-trailer`
- [x] install [`react-player`](https://www.npmjs.com/package/react-player)
- [x] create two new fetches for trailers from TMDB-API
- [x] create `Videoframe` component
- [x] Add `Videocomponent` to `MovieDetailsPage`and `SeriesDetailPage`
- [x] Test on Browser: Safari, Chrome and Firefox with Desktop PC, iPhone 11, iPad Air 2
