### ISSUE TITLE
[US-23] settings & info

### ISSUE THREAD

**Issue by Sven-Lyco** [Sven-Lyco/capstone-project#43]
## Value Proposition

**As a** User
**I need** an info page
**to be able to** know what this app is about

## Description

A new page displayed a small description about the app with a link to TMDB API and JustWatch.
A toggle switch should also be displayed so that the user can decide whether he wants to see the background image or the trailer on the details pages.

## Acceptance Criteria

- [x] A small description describes the  App
- [x] A Link to TMDB is implemented with the Logo
- [x] The toggle switch, sets the setting to display the background image or the movie

## Tasks

- [x] Create feature branch `info-page`
- [x] Create Info Page
- [x] Create toggle-switch 
- [x] Add toggle switch to info page
- [x] Update conditional rendering on detail pages
- [x] Test on Browser: Safari, Chrome and Firefox with Desktop PC, iPhone 11, iPad Air 2
