### ISSUE TITLE
[US-24] Rating Circle

### ISSUE THREAD

**Issue by Sven-Lyco** [Sven-Lyco/capstone-project#48]
## Value Proposition

**As a** User
**I need** a rating circle
**to be able to** know the rating of a movie or series

## Description

a rating circle shows the rating of a movie or series near the poster on the detailpage

## Acceptance Criteria

- [x] the rating is displayed near the poster
- [x] the rating circle is accessible

## Tasks

- [x] create feature branch `rating-circle`
- [x] install [`react-circular-progressbar`](https://www.npmjs.com/package/react-circular-progressbar)
- [x] create `RatingCircle` Component
- [x] add `RatingCircle` to `SeriesDetailPage` and `MovieDetailsPage`
- [x] test on Browser: Safari, Chrome and Firefox with Desktop PC, iPhone 11, iPad Air 2
