### ISSUE TITLE
[US-05] add watchlist

### ISSUE THREAD

**Issue by Sven-Lyco** [Sven-Lyco/capstone-project#5]
## Value Proposition

**As a** User
**I need** a watchlist
**to be able to** add interesting movies and series to a list to have a better overview of what I want to watch

## Description
<img src="https://user-images.githubusercontent.com/98020906/159945327-4a086576-d7ca-4998-be3a-c6215aa3b0e6.png" alt="Picture of User Story 5" height="500">

## Acceptance Criteria

- [x] Navigation is updated with a List-Icon
- [x] Plus-Button adds the Movie or Serie to a Watchlist
- [x] Plus-Button switches to an "X" to delete the Movie or Serie from Watchlist
- [x] The Watchlist Page contains Series and Movies added by the User
- [x] Movie and Series are displayed as a grid
- [x] If the List is Empty an Information should be displayed

## Tasks

- [x] Create feature branch `watchlist`
- [x] Update `Navigation` with Storybook and Testing
- [x] Build `ButtonAdd` with storybook
- [x] Test `ButtonAdd`
- [x] Create a `Watchlist` Page
- [x] Test `Watchlist` Page
- [x] Add `Watchlist` Page to `App`
- [x] Test on Browser: Safari, Chrome and Firefox with Desktop PC, iPhone 11, iPad Air 2
