### ISSUE TITLE
[US-25] code refactoring part 2

### ISSUE THREAD

**Issue by Sven-Lyco** [Sven-Lyco/capstone-project#50]
## Value Proposition

**As a** Developer
**I need** an app with clean code
**to be able to** have a good code structure / maintain the app more easily

## Description
Code refactoring

## Acceptance Criteria

- [x] The length of the code is reduced and more efficient

## Tasks

- [x] create feature branch `code-refactoring-2`
- [x] look for unnecessary code
- [x] check/update specs
- [x] check/update stories
- [x] check accessibility
- [x] check that code is semantically correct
- [x] create components for styling purposes if necessary
- [x] test on browser: Safari, Chrome and Firefox with Desktop PC, iPhone 11, iPad Air 2
