### ISSUE TITLE
[US-26] Toastify

### ISSUE THREAD

**Issue by Sven-Lyco** [Sven-Lyco/capstone-project#51]
## Value Proposition

**As a** User
**I need** a better information about my actions
**to be able to** understand what happens when I interact with the interface

## Description

A Notification will pop up on bottom centered, when the User adds or delete a movie or series to the watchlist

## Acceptance Criteria

- [x] the notification pops up by click "add to watchlist" for the movie or series with an information "zur Watchlist hinzugefügt" 
- [x] the notification pops up by click "delete from watchlist" for the movie or series with an information "von Watchlist entfernt"

## Tasks

- [x] create feature branch `toastify`
- [x] install [`react-toastify`](https://github.com/fkhadra/react-toastify)
- [x] implement toastify into the project
   - [x] configure toastify messages
   - [x] update functions
- [x] test on Browser: Safari, Chrome and Firefox with Desktop PC, iPhone 11, iPad Air 2
