### ISSUE TITLE
[US-06] add-local-storage

### ISSUE THREAD

**Issue by Sven-Lyco** [Sven-Lyco/capstone-project#6]
## Value Proposition

**As a** User
**I need** my added Movies and Series from the Watchlist to be saved
**to be able to** still have access to movies and series i want to watch

## Description
Add local storage to save the movies and series on Watchlist when the app is reloaded or reopened after closing

## Acceptance Criteria

- [x] Movies and Series persist when the app is reopened or reloaded

## Tasks

- [x] create feature branch `add-local-storage`
- [x] add `localStorage()` to App
- [x] Test on Browser: Safari, Chrome and Firefox with Desktop PC, iPhone 11, iPad Air 2
