### ISSUE TITLE
[US-07] get seasons and episodes

### ISSUE THREAD

**Issue by Sven-Lyco** [Sven-Lyco/capstone-project#7]
## Value Proposition

**As a** User
**I need** the listing of seasons and episodes
**to be able to** to know how many seasons and episodes a series has

## Description
<img src="https://user-images.githubusercontent.com/98020906/160171400-aaed4f98-d425-4606-b1b8-6ba43fa89e2b.png" alt="Picture of User Story 7" width="700">

## Acceptance Criteria

- [x] When Button "Details" is clicked the information about the Series is shown
- [x] When Button "Episoden" is clicked, a List of Seasons is displayed as a scrollable grid
- [x] When the Button e.g. "Staffel 1" is clicked, the information about the Season is displayed and a list of all Episodes

## Tasks

- [x] create feature branch `seasons-episodes`
- [x] Build an `InnerNavigation` Component with two Buttons and Storybook
- [x] Test `InnerNavigation`
- [x] Build `SeasonHeader` Component with Storybook
- [x] Test `SeasonHeader`
- [x] Build `EpisodeCard` Component with Storybook
- [x] Test `EpisodeCard`
- [x] Test on Browser: Safari, Chrome and Firefox with Desktop PC, iPhone 11, iPad Air 2
