### ISSUE TITLE
[US-08] get series cast

### ISSUE THREAD

**Issue by Sven-Lyco** [Sven-Lyco/capstone-project#8]
## Value Proposition

**As a** User
**I need** a list of the cast
**to be able to** know which actor plays which character

## Description

<img src="https://user-images.githubusercontent.com/98020906/160286423-28b3f253-2095-492f-a1e3-b0b593543afd.png" alt="Picture of User Story 8" width="300">

## Acceptance Criteria

- [x] The Cast is shown in the Details, after the Storyline
- [x] A List of the Cast is horizontally scrollable
- [x] If there is no picture of an actor available, a placeholder image is shown
- [x] The Name of the Actor and the character name are displayed under the picture

## Tasks

- [x] create feature branch `series-cast`
- [x] build `Actor` Component with Storybook
- [x] test `Actor` Component
- [x] build `CastList` Component with `Actor` Components in Storybook as a Grid
- [x] test `CastList`
- [x] Test on Browser: Safari, Chrome and Firefox with Desktop PC, iPhone 11, iPad Air 2
