### ISSUE TITLE
[US-09] get movies cast

### ISSUE THREAD

**Issue by Sven-Lyco** [Sven-Lyco/capstone-project#9]
## Value Proposition

**As a** User
**I need** a list of the cast
**to be able to** know which actor has which character

## Description

<img src="https://user-images.githubusercontent.com/98020906/160286480-cb1ac584-18bf-4ace-9e77-031a2c43b120.png" alt="Picture of User Story 9" width="300">

## Acceptance Criteria

- [x] The Cast is shown after the Storyline
- [x] A List of the Cast is shown as a scrollable Grid
- [x] If there is no picture of an actor available, a placeholder image is shown
- [x] The Name of the Actor and the Name of his Character is displayed under the picture

## Tasks

- [x] create feature branch `movies-cast`
- [x] implement `CastList`Component to `MovieDetailsPage`
- [x] Test on Browser: Safari, Chrome and Firefox with Desktop PC, iPhone 11, iPad Air 2
